### ISSUE TITLE
Is anything wrong I wrote？

### ISSUE THREAD

**Issue by sannnyu** [wishtack/gitbook-printer#3]
![image](https://user-images.githubusercontent.com/16554316/41019246-66f93b80-6990-11e8-8176-4306ccaeb0f3.png)

**Comment by yjaaidi** [comment]
Hi @SylvesterLi ! It looks good but could you try with Node 10.3.0?
Thank you in advance.

**Comment by yjaaidi** [comment]
Hi @SylvesterLi!
Could you please update the package `yarn global upgrade @wishtack/gitbook-printer` or `npm update -g @wishtack/gitbook-printer`?
I just released a new version to make it compatible with more NodeJS versions.

**Comment by sannnyu** [comment]
![image](https://user-images.githubusercontent.com/16554316/41031170-9a9812fa-69b2-11e8-8c3e-c3a0f6404d36.png)

It still seems not work well...Oh .. forget to say, I am using 8.9.3 version node

**Comment by yjaaidi** [comment]
Hi @SylvesterLi!

Sorry for responding so late.

Is it the right path for your `summary.md`? You should point the summary in your filesystem for the moment.

**Comment by sannnyu** [comment]
Yeah,it seems my operation was wrong and I did not notice it needed a SUMMARY.md at local.

after I navigate to my local repository just sync , and do it again , the error occurred.(Error in the picture below)

![image](https://user-images.githubusercontent.com/16554316/41400218-1bf0ee0c-6fef-11e8-84d0-aa43ddc56343.png)

and I try again

![image](https://user-images.githubusercontent.com/16554316/41400248-35ad02b8-6fef-11e8-89b0-184b113235ad.png)

![image](https://user-images.githubusercontent.com/16554316/41400274-463ce512-6fef-11e8-93f0-679d3f7b2523.png)

It still not works..What a pity,hahahah

**Comment by yjaaidi** [comment]
Oh! That's weird.
Could you please download the latest version `npm install -g @wishtack/gitbook-printer`? It should be the 0.1.4.

Here's the output I get.

https://filebin.net/vn3sswgls1c3rbz0/gitbook.pdf?t=p6ikrqpr

**Comment by qn0x** [comment]
I suspect it has something to do with Windows using backslash within paths(?)  
Had a similar error when trying it with Windows. The same command worked on Linux for me.

**Comment by sannnyu** [comment]
Not work，it is still 404.
And my generated files are different with yours，yours is a single PDF，but mine is several PDF.
![image](https://user-images.githubusercontent.com/16554316/41466965-19b5ae8c-70d7-11e8-9d8b-4528f80b36b0.png)


![image](https://user-images.githubusercontent.com/16554316/41496419-59bbdf9c-7172-11e8-827c-65ef14838a56.png)

Now I created a new Linux VM，but it seems I missed some   @@components?
@qn0x @yjaaidi

**Comment by yjaaidi** [comment]
Hi @qn0x @SylvesterLi ,

Sorry for responding so late. I just found the origin of the issue and fixed it in the latest 0.1.5 release.

1. When you tried on windows, you had an issue due to the extra `/` at the end of the URL. You have to use `https://wicrosoft.gitbook.io/syli-notebook` instead of `https://wicrosoft.gitbook.io/syli-notebook/` or simply upgrade to `@wishtack/gitbook-printer` 0.1.5.

2. For merging the partial files, I am using `easy-pdf-merge` which seems to try to use the best solution provided by the hosting operating system and it seems to fail on windows. You still can merge your partials manually using online tools like https://www.ilovepdf.com/merge_pdf.

3. @SylvesterLi, the error you had on linux is related to NodeJS. You need to use a more recent version that supports the `async / await` syntax (>= 7.6).

Thank you guys for your feedback and I hope that my indications will be helpful.

**Comment by sannnyu** [comment]
Thanks to your help ， it really works as I expect ！ It is very helpful. 
BTW,although it works well，it still has some errors which has no impact with it.
![image](https://user-images.githubusercontent.com/16554316/41594525-4458bfa4-73f6-11e8-84bc-3b4e2dc4f385.png)

And, I have some advice of improvement.
The converted PDF is little different from what web page displays.
Such as this Image:
![image](https://user-images.githubusercontent.com/16554316/41594896-8fe49064-73f7-11e8-9c89-a3ccf0fbf3e0.png)

When you free，you can fix some differences like this.
Anyway,your work is awesome! REALLY HELPFUL！
Thanks！！

**Comment by yjaaidi** [comment]
Good it helped!
Thank you for your feedback.
Gitbook will soon have a pdf export feature ;)
